package responses

type UserResp struct {
	Count  int        `json:"count"`
	Items  []Campaign `json:"items"`
	Offset int        `json:"offset"`
}

type User struct {
	Username       string      `json:"username"`
	ActiveBanners  int         `json:"active_banners"`
	Currency       string      `json:"currency"`
	BranchUsername interface{} `json:"branch_username"`
	EmailSettings  []struct {
		Active bool   `json:"active"`
		Type   string `json:"type"`
		Email  string `json:"email"`
	} `json:"email_settings"`
	ID             int         `json:"id"`
	Partner        interface{} `json:"partner"`
	AdditionalInfo struct {
		Name       string `json:"name"`
		ClientName string `json:"client_name"`
		ClientInfo string `json:"client_info"`
		Phone      string `json:"phone"`
		Address    string `json:"address"`
		Email      string `json:"email"`
	} `json:"additional_info"`
	AdditionalEmails []string `json:"additional_emails"`
	Agency           struct {
		IsBuyer              bool   `json:"is_buyer"`
		IsAffiliate          bool   `json:"is_affiliate"`
		OverridingCommission string `json:"overriding_commission"`
		BuyerCommission      string `json:"buyer_commission"`
	} `json:"agency"`
	AgencyUsername interface{} `json:"agency_username"`
	AllowedGeo     []int       `json:"allowed_geo"`
	Branch         struct {
		WithClients interface{} `json:"with_clients"`
	} `json:"branch"`
	Email             string        `json:"email"`
	MaxActiveBanners  interface{}   `json:"max_active_banners"`
	Status            string        `json:"status"`
	AvailableMailings []string      `json:"available_mailings"`
	Firstname         string        `json:"firstname"`
	Lastname          string        `json:"lastname"`
	Mailings          []string      `json:"mailings"`
	Notifications     []interface{} `json:"notifications"`
	RequiredGeo       []interface{} `json:"required_geo"`
	Types             []string      `json:"types"`
	Permissions       struct {
		CanUseVkGroups                         bool `json:"can_use_vk_groups"`
		CanCreateMacBasedAudiences             bool `json:"can_create_mac_based_audiences"`
		CanTransferSplitMoney                  bool `json:"can_transfer_split_money"`
		CanSetUpAuditPixels                    bool `json:"can_set_up_audit_pixels"`
		CanUseContextImport                    bool `json:"can_use_context_import"`
		CanJoinAgency                          bool `json:"can_join_agency"`
		CanUseContextSourceIdsList             bool `json:"can_use_context_source_ids_list"`
		CanUseDeviceIDLists                    bool `json:"can_use_device_id_lists"`
		CanViewAudienceID                      bool `json:"can_view_audience_id"`
		CanUseDashboard                        bool `json:"can_use_dashboard"`
		CanAccessAdmin                         bool `json:"can_access_admin"`
		CanManageRbmedia                       bool `json:"can_manage_rbmedia"`
		CanUseDatasourceCampaign               bool `json:"can_use_datasource_campaign"`
		CanViewStatReports                     bool `json:"can_view_stat_reports"`
		CanUseSegmentsMarkup                   bool `json:"can_use_segments_markup"`
		CanUseMassUpload                       bool `json:"can_use_mass_upload"`
		CanViewPackageID                       bool `json:"can_view_package_id"`
		CanViewClients                         bool `json:"can_view_clients"`
		CanUseIntegrationType                  bool `json:"can_use_integration_type"`
		CanUseMultiaccounts                    bool `json:"can_use_multiaccounts"`
		CanCreateClients                       bool `json:"can_create_clients"`
		CanUseCustomAudiences                  bool `json:"can_use_custom_audiences"`
		CanViewRemarketing                     bool `json:"can_view_remarketing"`
		CanCreateCustomAudiences               bool `json:"can_create_custom_audiences"`
		CanUsePartnerImageTypes                bool `json:"can_use_partner_image_types"`
		CanUseTargetingMobileApps              bool `json:"can_use_targeting_mobile_apps"`
		CanUseShareSource                      bool `json:"can_use_share_source"`
		CanUseApixelsMarkup                    bool `json:"can_use_apixels_markup"`
		CanUseSources4Interests                bool `json:"can_use_sources4interests"`
		CanUsePartnerMediation                 bool `json:"can_use_partner_mediation"`
		CanUseContext2                         bool `json:"can_use_context2"`
		CanUseRules                            bool `json:"can_use_rules"`
		CanUseDatasources                      bool `json:"can_use_datasources"`
		CanUseBlackLists                       bool `json:"can_use_black_lists"`
		CanCreatePads                          bool `json:"can_create_pads"`
		CanDeleteClients                       bool `json:"can_delete_clients"`
		CanViewVkGroups                        bool `json:"can_view_vk_groups"`
		CanSetUpExternalAuditViewability       bool `json:"can_set_up_external_audit_viewability"`
		CanSeeRemarketingUsersListMismatch     bool `json:"can_see_remarketing_users_list_mismatch"`
		CanUsePricelistCars                    bool `json:"can_use_pricelist_cars"`
		CanUsePartnerExtraTopics               bool `json:"can_use_partner_extra_topics"`
		CanUsePartnerTokens                    bool `json:"can_use_partner_tokens"`
		CanNotUseNewCampaignCreation           bool `json:"can_not_use_new_campaign_creation"`
		CanCreateAds                           bool `json:"can_create_ads"`
		CanUseAdvancedBlackLists               bool `json:"can_use_advanced_black_lists"`
		CanShareCustomAudiences                bool `json:"can_share_custom_audiences"`
		CanViewVideomrc                        bool `json:"can_view_videomrc"`
		CanTrackMacOfflineConversions          bool `json:"can_track_mac_offline_conversions"`
		CanViewTransactions                    bool `json:"can_view_transactions"`
		CanUsePartnerCpmFloor                  bool `json:"can_use_partner_cpm_floor"`
		CanUseSearchPhrasesSuggestions         bool `json:"can_use_search_phrases_suggestions"`
		CanUseLookalikeAudiences               bool `json:"can_use_lookalike_audiences"`
		CanUseDiseasesTargeting                bool `json:"can_use_diseases_targeting"`
		CanViewPlacementsStat                  bool `json:"can_view_placements_stat"`
		CanTrackOfflineConversions             bool `json:"can_track_offline_conversions"`
		CanModifyContextHelp                   bool `json:"can_modify_context_help"`
		CanUseSegmentsIP                       bool `json:"can_use_segments_ip"`
		CanUseWeatherTargeting                 bool `json:"can_use_weather_targeting"`
		CanCreateTestCampaigns                 bool `json:"can_create_test_campaigns"`
		CanUseSegments                         bool `json:"can_use_segments"`
		CanViewMoney                           bool `json:"can_view_money"`
		CanUseDmp                              bool `json:"can_use_dmp"`
		CanUsePadCategoryTargeting             bool `json:"can_use_pad_category_targeting"`
		CanUseBrowserTargetings                bool `json:"can_use_browser_targetings"`
		CanRegisterObserver                    bool `json:"can_register_observer"`
		CanViewManagerClients                  bool `json:"can_view_manager_clients"`
		CanManagePanel                         bool `json:"can_manage_panel"`
		CanUseFunnel                           bool `json:"can_use_funnel"`
		CanUseVkApps                           bool `json:"can_use_vk_apps"`
		CanUseDirectDeals                      bool `json:"can_use_direct_deals"`
		CanSetUpExternalAuditViewabilityMoatID bool `json:"can_set_up_external_audit_viewability_moat_id"`
		CanUseDmpStatistics                    bool `json:"can_use_dmp_statistics"`
		CanUseGenrepd                          bool `json:"can_use_genrepd"`
		CanUseMediateka                        bool `json:"can_use_mediateka"`
		CanCreateTransactions                  bool `json:"can_create_transactions"`
		CanCreateAgencyTransactions            bool `json:"can_create_agency_transactions"`
		CanUseDepositForm                      bool `json:"can_use_deposit_form"`
	} `json:"permissions"`
	Account struct {
		ABalance            string   `json:"a_balance"`
		IsNonresident       bool     `json:"is_nonresident"`
		Flags               []string `json:"flags"`
		CurrencyBalanceHold string   `json:"currency_balance_hold"`
		Balance             string   `json:"balance"`
		Type                string   `json:"type"`
		ID                  int      `json:"id"`
	} `json:"account"`
	Language     string      `json:"language"`
	InfoCurrency string      `json:"info_currency"`
	Dmp          interface{} `json:"dmp"`
}
